project_id = "ouhfgazomdmirdazvjys"

[functions.send-contact-to-slack]
verify_jwt = false

[functions.static-file]
verify_jwt = false

[functions.translate-content]
verify_jwt = false

[functions.generate-meta-description]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false
