-- Phase 1: Add all English translation keys (skip duplicates)
-- Using ON CONFLICT DO NOTHING to safely add only new keys

INSERT INTO translations (translation_key, language_code, translated_text, approved, page_location, context) VALUES
-- WhyNoddi Component
('why_noddi.title', 'en', 'Stop juggling tools. Start running operations.', true, 'homepage', 'Main section title'),
('why_noddi.subtitle', 'en', 'Most automotive service providers patch together 5+ tools. Noddi replaces them all.', true, 'homepage', 'Section subtitle'),
('why_noddi.before.title', 'en', 'Before Noddi', true, 'homepage', 'Card title for before state'),
('why_noddi.after.title', 'en', 'With Noddi', true, 'homepage', 'Card title for after state'),
('why_noddi.before.item_1', 'en', 'Multiple disconnected tools', true, 'homepage', 'Problem item'),
('why_noddi.before.item_2', 'en', 'Manual data entry across systems', true, 'homepage', 'Problem item'),
('why_noddi.before.item_3', 'en', 'Spreadsheet chaos', true, 'homepage', 'Problem item'),
('why_noddi.before.item_4', 'en', 'Lost customer follow-ups', true, 'homepage', 'Problem item'),
('why_noddi.after.item_1', 'en', 'One unified platform', true, 'homepage', 'Solution item'),
('why_noddi.after.item_2', 'en', 'Automatic data synchronization', true, 'homepage', 'Solution item'),
('why_noddi.after.item_3', 'en', 'Real-time operational visibility', true, 'homepage', 'Solution item'),
('why_noddi.after.item_4', 'en', 'Automated customer engagement', true, 'homepage', 'Solution item'),
('why_noddi.button_cta', 'en', 'See How It Works', true, 'homepage', 'CTA button text'),

-- HowItWorks Component
('how_it_works.title', 'en', 'How Noddi Powers Your Operations', true, 'homepage', 'Section title'),
('how_it_works.subtitle', 'en', 'From customer booking to back-office automation—all in one unified platform', true, 'homepage', 'Section subtitle'),
('how_it_works.step_1.title', 'en', 'Customer books service', true, 'homepage', 'Step 1 title'),
('how_it_works.step_1.description', 'en', 'Online booking or in-garage entry', true, 'homepage', 'Step 1 description'),
('how_it_works.step_1.details', 'en', 'Mobile + desktop support with one-minute funnel', true, 'homepage', 'Step 1 additional details'),
('how_it_works.step_2.title', 'en', 'Platform auto-plans routes & capacity', true, 'homepage', 'Step 2 title'),
('how_it_works.step_2.description', 'en', 'Proprietary optimization algorithms', true, 'homepage', 'Step 2 description'),
('how_it_works.step_2.details', 'en', 'Real-time resource allocation and workforce dispatch', true, 'homepage', 'Step 2 additional details'),
('how_it_works.step_3.title', 'en', 'Technicians execute with Noddi Worker app', true, 'homepage', 'Step 3 title'),
('how_it_works.step_3.description', 'en', 'Native app for mobile + garage workflows', true, 'homepage', 'Step 3 description'),
('how_it_works.step_3.details', 'en', 'Standardized inspection capture and tire sales', true, 'homepage', 'Step 3 additional details'),
('how_it_works.step_4.title', 'en', 'System captures data → triggers actions', true, 'homepage', 'Step 4 title'),
('how_it_works.step_4.description', 'en', 'Auto-recall campaigns, tire sales, inventory updates', true, 'homepage', 'Step 4 description'),
('how_it_works.step_4.details', 'en', 'No manual follow-up needed—fully automated', true, 'homepage', 'Step 4 additional details'),
('how_it_works.step_label', 'en', 'Step {index}', true, 'homepage', 'Step label with index placeholder'),
('how_it_works.caption_main', 'en', 'It''s not automation. It''s orchestration.', true, 'homepage', 'Main caption tagline'),
('how_it_works.caption_sub', 'en', 'One platform. Every function. Zero friction.', true, 'homepage', 'Sub caption tagline'),

-- WhyItMatters Component
('why_it_matters.title', 'en', 'Why Our Integrated Platform Matters', true, 'homepage', 'Section title'),
('why_it_matters.subtitle', 'en', 'When your booking system and ERP speak the same language, everything just works', true, 'homepage', 'Section subtitle'),
('why_it_matters.tab_problem.label', 'en', 'The Industry Problem', true, 'homepage', 'Tab 1 label'),
('why_it_matters.tab_opportunity.label', 'en', 'Opportunity & Traction', true, 'homepage', 'Tab 2 label'),
('why_it_matters.tab_advantage.label', 'en', 'Integrated Tech Advantage', true, 'homepage', 'Tab 3 label'),
('why_it_matters.problem.title', 'en', 'The Car Maintenance Experience Is Broken', true, 'homepage', 'Problem section title'),
('why_it_matters.problem.subtitle', 'en', 'Traditional automotive services are failing to meet modern customer expectations', true, 'homepage', 'Problem section subtitle'),
('why_it_matters.problem.card_1.title', 'en', 'Inconvenient & Time-Consuming', true, 'homepage', 'Problem card 1 title'),
('why_it_matters.problem.card_1.text', 'en', 'Customers waste hours driving to garages, waiting for service, and dealing with manual processes', true, 'homepage', 'Problem card 1 text'),
('why_it_matters.problem.card_2.title', 'en', 'Poor Customer Experience', true, 'homepage', 'Problem card 2 title'),
('why_it_matters.problem.card_2.text', 'en', 'Hidden fees, lack of transparency, and unreliable communication damage trust and satisfaction', true, 'homepage', 'Problem card 2 text'),
('why_it_matters.problem.card_3.title', 'en', 'Limited Digital Presence', true, 'homepage', 'Problem card 3 title'),
('why_it_matters.problem.card_3.text', 'en', 'Most providers aren''t digital—still relying on phone calls and manual scheduling', true, 'homepage', 'Problem card 3 text'),
('why_it_matters.problem.card_4.title', 'en', 'Industry NPS: 20-30', true, 'homepage', 'Problem card 4 title'),
('why_it_matters.problem.card_4.text', 'en', 'Low customer satisfaction scores indicate widespread dissatisfaction with current service models', true, 'homepage', 'Problem card 4 text'),
('why_it_matters.opportunity.title', 'en', 'Convenience Services Are Exploding', true, 'homepage', 'Opportunity section title'),
('why_it_matters.opportunity.subtitle', 'en', 'The market is growing rapidly, and Noddi is leading the transformation', true, 'homepage', 'Opportunity section subtitle'),
('why_it_matters.opportunity.metric_1.value', 'en', '>49%', true, 'homepage', 'Metric 1 value'),
('why_it_matters.opportunity.metric_1.label', 'en', 'Annual Market Growth', true, 'homepage', 'Metric 1 label'),
('why_it_matters.opportunity.metric_1.description', 'en', 'Convenience services are the fastest-growing segment', true, 'homepage', 'Metric 1 description'),
('why_it_matters.opportunity.metric_2.value', 'en', '20,000+', true, 'homepage', 'Metric 2 value'),
('why_it_matters.opportunity.metric_2.label', 'en', 'Bookings Completed — and growing', true, 'homepage', 'Metric 2 label'),
('why_it_matters.opportunity.metric_2.description', 'en', 'Proven platform with real commercial traction', true, 'homepage', 'Metric 2 description'),
('why_it_matters.opportunity.metric_3.value', 'en', 'NPS ~90', true, 'homepage', 'Metric 3 value'),
('why_it_matters.opportunity.metric_3.label', 'en', 'Customer Satisfaction', true, 'homepage', 'Metric 3 label'),
('why_it_matters.opportunity.metric_3.description', 'en', '3x better than industry average (20-30)', true, 'homepage', 'Metric 3 description'),
('why_it_matters.opportunity.metric_4.value', 'en', '4', true, 'homepage', 'Metric 4 value'),
('why_it_matters.opportunity.metric_4.label', 'en', 'Paying SaaS Partners', true, 'homepage', 'Metric 4 label'),
('why_it_matters.opportunity.metric_4.description', 'en', 'Take-rate per booking model validated', true, 'homepage', 'Metric 4 description'),
('why_it_matters.opportunity.metric_5.value', 'en', '€65B', true, 'homepage', 'Metric 5 value'),
('why_it_matters.opportunity.metric_5.label', 'en', 'Addressable Market', true, 'homepage', 'Metric 5 label'),
('why_it_matters.opportunity.metric_5.description', 'en', 'Massive opportunity for platform expansion', true, 'homepage', 'Metric 5 description'),
('why_it_matters.opportunity.metric_6.value', 'en', '>€200M', true, 'homepage', 'Metric 6 value'),
('why_it_matters.opportunity.metric_6.label', 'en', 'License Revenue Potential', true, 'homepage', 'Metric 6 label'),
('why_it_matters.opportunity.metric_6.description', 'en', 'Annual recurring revenue opportunity', true, 'homepage', 'Metric 6 description'),
('why_it_matters.advantage.title', 'en', 'One Platform. One Source of Truth.', true, 'homepage', 'Advantage section title'),
('why_it_matters.advantage.subtitle', 'en', 'Noddi doesn''t just provide a booking flow — we offer a fully automated logistics platform that eliminates API sync issues because the ERP backend and booking frontend share the same data model and automation engine', true, 'homepage', 'Advantage section subtitle'),
('why_it_matters.advantage.callout', 'en', 'When your booking system and ERP speak the same language, everything just works.', true, 'homepage', 'Advantage callout'),
('why_it_matters.advantage.table.header_1', 'en', 'Problem', true, 'homepage', 'Table header 1'),
('why_it_matters.advantage.table.header_2', 'en', 'What Happens in Disconnected Systems', true, 'homepage', 'Table header 2'),
('why_it_matters.advantage.table.header_3', 'en', 'Noddi''s Integrated Approach', true, 'homepage', 'Table header 3'),
('why_it_matters.advantage.pain_1.problem', 'en', 'Tire sales can''t be automated', true, 'homepage', 'Pain point 1 problem'),
('why_it_matters.advantage.pain_1.disconnected', 'en', 'Manual cross-checking, delays, errors', true, 'homepage', 'Pain point 1 disconnected'),
('why_it_matters.advantage.pain_1.approach', 'en', 'Fully integrated tire sales tied to inventory & quoting', true, 'homepage', 'Pain point 1 approach'),
('why_it_matters.advantage.pain_2.problem', 'en', 'Poor recall logic', true, 'homepage', 'Pain point 2 problem'),
('why_it_matters.advantage.pain_2.disconnected', 'en', 'Static campaigns, low relevance', true, 'homepage', 'Pain point 2 disconnected'),
('why_it_matters.advantage.pain_2.approach', 'en', 'Recall campaigns driven by capacity, utilization, and data', true, 'homepage', 'Pain point 2 approach'),
('why_it_matters.advantage.pain_3.problem', 'en', 'Sync issues when booking changes', true, 'homepage', 'Pain point 3 problem'),
('why_it_matters.advantage.pain_3.disconnected', 'en', 'Broken flows, double bookings', true, 'homepage', 'Pain point 3 disconnected'),
('why_it_matters.advantage.pain_3.approach', 'en', 'Real-time sync across booking, backend, shop', true, 'homepage', 'Pain point 3 approach'),
('why_it_matters.advantage.pain_4.problem', 'en', 'Lane optimization breaks', true, 'homepage', 'Pain point 4 problem'),
('why_it_matters.advantage.pain_4.disconnected', 'en', 'Digital → analog friction upon arrival', true, 'homepage', 'Pain point 4 disconnected'),
('why_it_matters.advantage.pain_4.approach', 'en', 'Seamless experience from booking to garage floor', true, 'homepage', 'Pain point 4 approach'),
('why_it_matters.advantage.pain_5.problem', 'en', 'Contactless visits are limited', true, 'homepage', 'Pain point 5 problem'),
('why_it_matters.advantage.pain_5.disconnected', 'en', 'Need in-person touchpoints', true, 'homepage', 'Pain point 5 disconnected'),
('why_it_matters.advantage.pain_5.approach', 'en', 'Fully self-servicable UI with mobile + in-lane support', true, 'homepage', 'Pain point 5 approach'),
('why_it_matters.advantage.pain_6.problem', 'en', 'Splitting across systems', true, 'homepage', 'Pain point 6 problem'),
('why_it_matters.advantage.pain_6.disconnected', 'en', 'Integration complexity + tech dependencies', true, 'homepage', 'Pain point 6 disconnected'),
('why_it_matters.advantage.pain_6.approach', 'en', 'We own both booking and ERP — one roadmap, one source of truth', true, 'homepage', 'Pain point 6 approach'),
('why_it_matters.advantage.mobile.disconnected_label', 'en', 'Disconnected Systems:', true, 'homepage', 'Mobile view label'),
('why_it_matters.advantage.mobile.approach_label', 'en', 'Noddi''s Approach:', true, 'homepage', 'Mobile view label'),

-- TrustProof Component
('trust_proof.title', 'en', 'Trusted by Service Professionals', true, 'homepage', 'Section title'),
('trust_proof.subtitle', 'en', 'Real results from real businesses—proven traction and customer satisfaction', true, 'homepage', 'Section subtitle'),
('trust_proof.metric_1.value', 'en', '20,000+', true, 'homepage', 'Metric 1 value'),
('trust_proof.metric_1.label', 'en', 'Bookings completed — and growing', true, 'homepage', 'Metric 1 label'),
('trust_proof.metric_1.description', 'en', 'Proven platform with real commercial success', true, 'homepage', 'Metric 1 description'),
('trust_proof.metric_2.value', 'en', '4', true, 'homepage', 'Metric 2 value'),
('trust_proof.metric_2.label', 'en', 'Paying SaaS Partners', true, 'homepage', 'Metric 2 label'),
('trust_proof.metric_2.description', 'en', 'Take-rate per booking model validated', true, 'homepage', 'Metric 2 description'),
('trust_proof.metric_3.value', 'en', '>49%', true, 'homepage', 'Metric 3 value'),
('trust_proof.metric_3.label', 'en', 'Annual Market Growth', true, 'homepage', 'Metric 3 label'),
('trust_proof.metric_3.description', 'en', 'Convenience services exploding', true, 'homepage', 'Metric 3 description'),
('trust_proof.metric_4.value', 'en', '€65B', true, 'homepage', 'Metric 4 value'),
('trust_proof.metric_4.label', 'en', 'Addressable Market', true, 'homepage', 'Metric 4 label'),
('trust_proof.metric_4.description', 'en', 'Massive expansion opportunity', true, 'homepage', 'Metric 4 description'),
('trust_proof.nps.title', 'en', 'Industry-Leading Customer Satisfaction', true, 'homepage', 'NPS section title'),
('trust_proof.nps.value', 'en', '~90', true, 'homepage', 'NPS score value'),
('trust_proof.nps.label', 'en', 'NPS Score', true, 'homepage', 'NPS label'),
('trust_proof.nps.callout', 'en', '3x better than industry average (20-30)', true, 'homepage', 'NPS callout'),
('trust_proof.nps.category_1.label', 'en', 'Overall', true, 'homepage', 'NPS category 1'),
('trust_proof.nps.category_2.label', 'en', 'Communication', true, 'homepage', 'NPS category 2'),
('trust_proof.nps.category_3.label', 'en', 'Ease of use', true, 'homepage', 'NPS category 3'),
('trust_proof.nps.category_4.label', 'en', 'Politeness', true, 'homepage', 'NPS category 4'),
('trust_proof.conversion.value', 'en', '40%', true, 'homepage', 'Conversion rate value'),
('trust_proof.conversion.label', 'en', 'Conversion Rate', true, 'homepage', 'Conversion label'),
('trust_proof.conversion.description', 'en', 'Our optimized 6-step booking funnel delivers industry-leading conversion rates, turning more visitors into customers.', true, 'homepage', 'Conversion description'),
('trust_proof.conversion.stat_1.label', 'en', 'Step completion rate', true, 'homepage', 'Conversion stat 1 label'),
('trust_proof.conversion.stat_1.value', 'en', '90%+', true, 'homepage', 'Conversion stat 1 value'),
('trust_proof.conversion.stat_2.label', 'en', 'Customer return rate', true, 'homepage', 'Conversion stat 2 label'),
('trust_proof.conversion.stat_2.value', 'en', '77.9%', true, 'homepage', 'Conversion stat 2 value'),
('trust_proof.conversion.stat_3.label', 'en', 'Booking abandonment', true, 'homepage', 'Conversion stat 3 label'),
('trust_proof.conversion.stat_3.value', 'en', '<10%', true, 'homepage', 'Conversion stat 3 value'),
('trust_proof.testimonials.title', 'en', 'What Customers Say', true, 'homepage', 'Testimonials section title'),

-- RapidOnboarding Component
('rapid_onboarding.title', 'en', 'Launch in Less Than 1 Day', true, 'homepage', 'Section title'),
('rapid_onboarding.badge', 'en', '< 24h', true, 'homepage', 'Time badge'),
('rapid_onboarding.subtitle', 'en', 'Onboard new partners in any geography with plug-and-play simplicity', true, 'homepage', 'Section subtitle'),
('rapid_onboarding.step_1.title', 'en', 'Draw service area', true, 'homepage', 'Step 1 title'),
('rapid_onboarding.step_1.description', 'en', 'Define your geographic coverage on the map', true, 'homepage', 'Step 1 description'),
('rapid_onboarding.step_2.title', 'en', 'Configure brand/logo', true, 'homepage', 'Step 2 title'),
('rapid_onboarding.step_2.description', 'en', 'Upload your branding assets and customize the look', true, 'homepage', 'Step 2 description'),
('rapid_onboarding.step_3.title', 'en', 'Upload price list', true, 'homepage', 'Step 3 title'),
('rapid_onboarding.step_3.description', 'en', 'Import your service pricing and packages', true, 'homepage', 'Step 3 description'),
('rapid_onboarding.step_4.title', 'en', 'Launch', true, 'homepage', 'Step 4 title'),
('rapid_onboarding.step_4.description', 'en', 'Enable automatic SEO and go live', true, 'homepage', 'Step 4 description'),
('rapid_onboarding.benefits.title', 'en', 'Key Benefits', true, 'homepage', 'Benefits section title'),
('rapid_onboarding.benefit_1', 'en', 'Expansion to new services/regions is plug-and-play', true, 'homepage', 'Benefit 1'),
('rapid_onboarding.benefit_2', 'en', 'Backend and frontend unified for rapid scaling', true, 'homepage', 'Benefit 2'),
('rapid_onboarding.benefit_3', 'en', 'No integration complexity or API dependencies', true, 'homepage', 'Benefit 3'),
('rapid_onboarding.benefit_4', 'en', 'Single configuration process for all services', true, 'homepage', 'Benefit 4'),
('rapid_onboarding.bottom_cta', 'en', 'Scale globally without technical barriers — Noddi handles the complexity', true, 'homepage', 'Bottom CTA text'),

-- TeamHighlight Component
('team_highlight.title', 'en', 'Built by Route-Planning Pioneers', true, 'homepage', 'Section title'),
('team_highlight.subtitle', 'en', 'World-class team combining deep technical expertise with business acumen', true, 'homepage', 'Section subtitle'),
('team_highlight.expertise_1.title', 'en', 'AI & Route Planning', true, 'homepage', 'Expertise 1 title'),
('team_highlight.expertise_1.description', 'en', 'Pioneers from Oda and delivery-tech startups', true, 'homepage', 'Expertise 1 description'),
('team_highlight.expertise_2.title', 'en', 'B2B Sales', true, 'homepage', 'Expertise 2 title'),
('team_highlight.expertise_2.description', 'en', 'Deep expertise in SaaS and enterprise sales', true, 'homepage', 'Expertise 2 description'),
('team_highlight.expertise_3.title', 'en', 'Operations', true, 'homepage', 'Expertise 3 title'),
('team_highlight.expertise_3.description', 'en', 'Proven track record in logistics and automation', true, 'homepage', 'Expertise 3 description'),
('team_highlight.footer_text', 'en', 'Our founding team brings together experience from Oda, leading delivery-tech startups, and enterprise software companies—combining cutting-edge AI, logistics automation, and B2B expertise to transform automotive services.', true, 'homepage', 'Footer text'),

-- PricingFAQ Component
('pricing_faq.question_1', 'en', 'Is there a free tier?', true, 'pricing', 'FAQ question 1'),
('pricing_faq.answer_1', 'en', 'No. Billing starts from your first euro of revenue. We believe in transparent, performance-based pricing that scales with your success—no free tier games, just fair pricing from day one.', true, 'pricing', 'FAQ answer 1'),
('pricing_faq.question_2', 'en', 'Why revenue-based pricing?', true, 'pricing', 'FAQ question 2'),
('pricing_faq.answer_2', 'en', 'Revenue-based pricing ensures you pay in proportion to the value you get from our platform. When you grow, we grow together. This alignment of incentives means we''re always working to help you succeed.', true, 'pricing', 'FAQ answer 2'),
('pricing_faq.question_3', 'en', 'How are rates calculated?', true, 'pricing', 'FAQ question 3'),
('pricing_faq.answer_3', 'en', 'Rates are calculated using a single-tier flat-rate system based on your monthly SaaS revenue. There are no complex tiers or sudden jumps—just straightforward percentage-based pricing that scales smoothly with your business.', true, 'pricing', 'FAQ answer 3'),
('pricing_faq.question_4', 'en', 'Do you offer discounts?', true, 'pricing', 'FAQ question 4'),
('pricing_faq.answer_4', 'en', 'Yes! We offer two types of contract discounts: a 3% discount for 6-month pre-payment contracts, and a 5% discount for annual contracts. These discounts provide significant savings while giving you budget predictability.', true, 'pricing', 'FAQ answer 4'),
('pricing_faq.question_5', 'en', 'Is there a minimum commitment?', true, 'pricing', 'FAQ question 5'),
('pricing_faq.answer_5', 'en', 'No minimum commitment is required for the standard pay-as-you-go model. However, if you opt for a contract with pre-payment, you''ll benefit from our discount rates while locking in predictable costs.', true, 'pricing', 'FAQ answer 5'),
('pricing_faq.question_6', 'en', 'What happens if my revenue changes?', true, 'pricing', 'FAQ question 6'),
('pricing_faq.answer_6', 'en', 'Your pricing automatically adjusts as your revenue changes. The rate you pay stays consistent, so your costs scale proportionally with your growth—no surprises, no manual adjustments needed.', true, 'pricing', 'FAQ answer 6'),
('pricing_faq.question_7', 'en', 'Are there any hidden fees?', true, 'pricing', 'FAQ question 7'),
('pricing_faq.answer_7', 'en', 'No hidden fees whatsoever. The usage fee includes everything: unlimited users, all features, updates, and support. What you see is what you pay—simple and transparent.', true, 'pricing', 'FAQ answer 7')
ON CONFLICT (translation_key, language_code) DO NOTHING;