// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouhfgazomdmirdazvjys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91aGZnYXpvbWRtaXJkYXp2anlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzI5OTEsImV4cCI6MjA3MDE0ODk5MX0.w5iC3BX6u5vrnr1fMj5HyYUwEtYRwsoTVx3oAQ2foCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});